name: CI/CD AWS S3

on:
  push:
    branches:
      - main

jobs:
  test:
    name: action test
    runs-on: ubuntu-latest
    steps:
      - name: check ls
        run: ls -al
      - name: clone repo
        uses: actions/checkout@v3
      - name: clone check ls
        run: ls -al
      - name: Set up environment variables
        run: |
          echo "VITE_KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }}" >> .env
          echo "VITE_BASE_URL=${{ secrets.BASE_URL }}" >> .env
      - name: Install dependencies
        run: npm install
      - name: Generate build
        run: npm run build
      - name: AWS IAM user set
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: upload to S3
        run: |
          aws s3 cp --recursive --region ap-northeast-2 dist s3://${{ secrets.BUCKET_NAME }}
